require_relative 'game'

game = Game.new
game.start_game


# FIX COORDINATES NOT READING BACKWARDS
#done

# FIX COMPUTER SHIP PLACEMENT/RENDERING INCORRECTLY WHEN HIT

# FIX NEVERENDING LOOP WHEN INCORRECT
# COORDINATES PROVIDED

# FIX END_GAME; RETURN TO MENU
